# Generated by Django 3.0.8 on 2020-08-15 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lissajouscurve',
            name='phase',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lissajouscurve',
            name='simulation_time',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='lissajouscurve',
            name='x_frequency',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lissajouscurve',
            name='y_frequency',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
