# Generated by Django 3.0.8 on 2020-08-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20200815_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='lissajouscurve',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
