# Generated by Django 3.0.8 on 2020-08-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20200817_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lissajouscurve',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='lissajouscurve',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='plots'),
        ),
    ]
